const GET_ALL_USER_INFO_REQUEST = 'users/GET_ALL_USER_INFO_REQUEST';
const GET_ALL_USER_INFO_SUCCESS = 'users/GET_ALL_USER_INFO_SUCCESS';
const GET_ALL_USER_INFO_FAILURE = 'users/GET_ALL_USER_INFO_FAILURE';

export {
    GET_ALL_USER_INFO_REQUEST,
    GET_ALL_USER_INFO_SUCCESS,
    GET_ALL_USER_INFO_FAILURE
}
